const translations = {
  en: {
    selectFilter: 'Select Filter Type',
    selectCity: 'Select City',
    selectDeity: 'Select Deity',
    selectType: 'Select Type',
    selectRadius: 'Select Radius',
    city: 'City',
    deity: 'Deity',
    type: 'Type',
    radius: 'Radius',
    startNavigation: 'Start Navigation',
    navigationSteps: 'Navigation Steps',
    loading: 'Loading Map...',
    header: '108 Divya Desams',
  },
  te: {
    selectFilter: 'ఫిల్టర్ ఎంచుకోండి',
    selectCity: 'నగరం ఎంచుకోండి',
    selectDeity: 'దేవత ఎంచుకోండి',
    selectType: 'రకం ఎంచుకోండి',
    selectRadius: 'ప్రాంతం ఎంచుకోండి',
    city: 'నగరం',
    deity: 'దేవత',
    type: 'రకం',
    radius: 'ప్రాంతం',
    startNavigation: 'నావిగేషన్ ప్రారంభించండి',
    navigationSteps: 'దిశ సూచనలు',
    loading: 'పటం లోడ్ అవుతోంది...',
    header: '108 దివ్యదేశాలు',
  },
  hi: {
    selectFilter: 'फ़िल्टर प्रकार चुनें',
    selectCity: 'शहर चुनें',
    selectDeity: 'देवता चुनें',
    selectType: 'प्रकार चुनें',
    selectRadius: 'त्रिज्या चुनें',
    city: 'शहर',
    deity: 'देवता',
    type: 'प्रकार',
    radius: 'त्रिज्या',
    startNavigation: 'नेविगेशन शुरू करें',
    navigationSteps: 'दिशा निर्देश',
    loading: 'मानचित्र लोड हो रहा है...',
    header: '१०८ दिव्य देशम',
  }
};

export default translations;
