/** ---------- UI Translations ---------- */
export const UI_TRANSLATIONS = {
  en: {
    selectFilter: "Select Filter",
    city: "City",
     state: "State", 
    nearby: "Nearby",
    all: "All",
    selectCity: "Select City",
     selectState: "Select State",
    searchPlaceholder: "Enter first 3 letters of temple or city name",
    permissionDenied: "Permission Denied",
    locationRequired: "Location permission is required",
    error: "Error",
    fetchError: "Unable to fetch temples. Please try again.",
    templeIdMissing: "Temple ID is missing",
    templeNotFound: "Temple not found",
    fetchDetailsError: "Failed to fetch temple details.",
    info: "Info",
     nearestTemples: "Nearest Temples",
    noNearestTemples: "No nearby temples found",
    templeDistance: "km away",
    noAdditionalDetails: "No additional details available for this temple.",
    loadDetailsError: "Failed to load details",
    routeError: "Route Error",
    selectItemError: "Failed to open the selected item.",
    mapLoading: "Loading map…",
    mainDeity: "Main Deity",
    showMore: "Show More",
    showLess: "Show Less",
    kmAway: "km away",
    noDescription: "No description available",
    noAdditionalInfo: "No additional details available",
    loadingTemples: "Loading temples...",
  },
  te: {
    selectFilter: "ఫిల్టర్ ఎంచుకోండి",
    city: "నగరం",
    state: "రాష్ట్రం",
    nearby: "సమీపంలో",

    all: "అన్నీ",
    nearestTemples: "సమీప ఆలయాలు",
    noNearestTemples: "సమీప ఆలయాలు కనుగొనబడలేదు",
    templeDistance: "కిమీ దూరంలో",
    selectCity: "నగరం ఎంచుకోండి",

     selectState: "రాష్ట్రం ఎంచుకోండి",
    searchPlaceholder: "మీరు వెతుకుతున్న ఆలయం పేరు లేదా నగర పేరు మొదటి 3 అక్షరాలు నమోదు చేయండి",
    permissionDenied: "అనుమతి నిరాకరించబడింది",
    locationRequired: "లొకేషన్ అనుమతి అవసరం",
    error: "లోపం",
    fetchError: "ఆలయాలను పొందడం విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    templeIdMissing: "ఆలయం ID లేదు",
    templeNotFound: "ఆలయం కనుగొనబడలేదు",
    fetchDetailsError: "ఆలయ వివరాలను పొందడం విఫలమైంది.",
    info: "సమాచారం",
    noAdditionalDetails: "ఈ ఆలయానికి అదనపు వివరాలు అందుబాటులో లేవు.",
    loadDetailsError: "వివరాలను లోడ్ చేయడం విఫలమైంది",
    routeError: "రూట్ లోపం",
    selectItemError: "ఎంచుకున్న అంశాన్ని తెరవడం విఫలమైంది.",
    mapLoading: "మ్యాప్ లోడ్ అవుతోంది…",
    mainDeity: "ప్రధాన దేవత",
    showMore: "మరింత చూపించు",
    showLess: "తక్కువ చూపించు",
    kmAway: "కి.మీ దూరంలో",
    noDescription: "వివరణ అందుబాటులో లేదు",
    noAdditionalInfo: "అదనపు వివరాలు అందుబాటులో లేవు",
    loadingTemples: "ఆలయాలు లోడ్ అవుతున్నాయి...",
  },
  ta: {
    selectFilter: "வடிகட்டியைத் தேர்ந்தெடுக்கவும்",
    city: "நகரம்",
    state: "மாநிலம்",
    nearby: "அருகில்",
    all: "அனைத்தும்",
    selectCity: "நகரத்தைத் தேர்ந்தெடுக்கவும்",
    selectState: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    searchPlaceholder: "கோவில் அல்லது நகரத்தின் முதல் 3 எழுத்துகளை உள்ளிடவும்",
    permissionDenied: "அனுமதி மறுக்கப்பட்டது",
    locationRequired: "இருப்பிட அனுமதி தேவை",
    error: "பிழை",
    fetchError: "கோவில்களை பெற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
    templeIdMissing: "கோவில் ID இல்லை",
    templeNotFound: "கோவில் கிடைக்கவில்லை",
    fetchDetailsError: "கோவில் விவரங்களை பெற முடியவில்லை.",
    info: "தகவல்",
    nearestTemples: "அருகிலுள்ள கோவில்கள்",
    noNearestTemples: "அருகில் கோவில்கள் இல்லை",
    templeDistance: "கிமீ தூரம்",
    noAdditionalDetails: "இந்த கோவிலுக்கு கூடுதல் விவரங்கள் இல்லை.",
    loadDetailsError: "விவரங்களை ஏற்ற முடியவில்லை",
    routeError: "வழித்தட பிழை",
    selectItemError: "தேர்ந்தெடுத்ததை திறக்க முடியவில்லை.",
    mapLoading: "வரைபடம் ஏற்றப்படுகிறது…",
    mainDeity: "மூலவர்",
    showMore: "மேலும் காண்க",
    showLess: "குறைவாக காண்க",
    kmAway: "கிமீ தூரம்",
    noDescription: "விளக்கம் இல்லை",
    noAdditionalInfo: "கூடுதல் விவரங்கள் இல்லை",
    loadingTemples: "கோவில்கள் ஏற்றப்படுகின்றன...",
  },
  hi: {
    selectFilter: "फ़िल्टर चुनें",
    city: "शहर",
    state: "राज्य",
    nearby: "पास में",
    all: "सभी",
    selectCity: "शहर चुनें",
    selectState: "राज्य चुनें",
    searchPlaceholder: "मंदिर या शहर के पहले 3 अक्षर दर्ज करें",
    permissionDenied: "अनुमति अस्वीकृत",
    locationRequired: "लोकेशन अनुमति आवश्यक है",
    error: "त्रुटि",
    fetchError: "मंदिर प्राप्त नहीं हो पाए। कृपया फिर से प्रयास करें।",
    templeIdMissing: "मंदिर आईडी नहीं है",
    templeNotFound: "मंदिर नहीं मिला",
    fetchDetailsError: "मंदिर विवरण प्राप्त नहीं हो सका।",
    info: "जानकारी",
    nearestTemples: "निकटतम मंदिर",
    noNearestTemples: "कोई पास का मंदिर नहीं मिला",
    templeDistance: "किमी दूर",
    noAdditionalDetails: "इस मंदिर के लिए अतिरिक्त विवरण उपलब्ध नहीं हैं।",
    loadDetailsError: "विवरण लोड नहीं हो सके",
    routeError: "रूट त्रुटि",
    selectItemError: "चयनित आइटम नहीं खुल सका।",
    mapLoading: "मानचित्र लोड हो रहा है…",
    mainDeity: "मुख्य देवता",
    showMore: "और देखें",
    showLess: "कम देखें",
    kmAway: "किमी दूर",
    noDescription: "विवरण उपलब्ध नहीं",
    noAdditionalInfo: "अतिरिक्त विवरण उपलब्ध नहीं",
    loadingTemples: "मंदिर लोड हो रहे हैं...",
  },
};

/** ---------- Deity detection ---------- */
export const TOKENS = {
  vishnu: [
    "vishnu","narayana","govinda","venkateswara","srinivasa","balaji",
    "విష్ణు","విష్ణువు","శ్రీ విష్ణు","నారాయణ","వెంకటేశ్వర","శ్రీనివాస","శ్రీనివాసుడు","గోవింద",
    "विष्णु","नारायण","गोविंद","वैंकटेश्वर","श्रीनिवास",
  ],
  rama: [
    "rama","sri rama","shri rama","sriram",
    "రామ","శ్రీరామ","శ్రీ రామ","రాముడు",
    "राम","श्रीराम","श्री राम",
  ],
  krishna: [
    "krishna","sri krishna","shri krishna","gopala","muralidhar","murali",
    "కృష్ణ","శ్రీకృష్ణ","శ్రీ కృష్ణ","గోపాల","గోవింద",
    "कृष्ण","श्रीकृष्ण","गोपाल","गोविंद",
  ],
  narasimha: [
    "narasimha","nrsimha","narsimha","narasimh",
    "నరసింహ","నృసింహ","నరసింహుడు","లక్ష్మీనరసింహ",
    "नरसिंह","नृसिंह","लक्ष्मीनरसिंह",
  ],
  durga: [
    "durga","devi","shakti",
    "దుర్గ","దుర్గమ్మ","దేవి",
    "दुर्गा","देवी","शक्ति",
  ],
  ganesha: [
    "ganesh","ganesha","vinayaka","ganapati","vinayak","pillaiyar",
    "గణేశ","గణపతి","వినాయక",
    "गणेश","गणपति","विनायक",
  ],
  subrahmanya: [
    "subrahmanya","subramanya","subrahmanyam","murugan","karthikeya","skanda","kumara",
    "సుబ్రహ్మణ్య","సుబ్రహ్మణ్యం","మురుగన్","కార్తికేయ","కుమారస్వామి",
    "सुब्रह्मण्य","कार्तिकेय","स्कन्द","मुरुगन",
  ],
  shiva: [
    "shiva","siva","mahadev","mahadeva","shankara","rudra","lingeshwara","lingam","linga",
    "శివ","శివుడు","పరమశివ","లింగేశ్వర","లింగం",
    "शिव","महादेव","शंकर","रुद्र","लिंगेश्वर","लिंगम्",
  ],
  // ADD after the shiva block:
  hanuman: [
    "hanuman","anjaneya","maruti","bajrangbali",
    "హనుమాన్","ఆంజనేయ","ఆంజనేయుడు","మారుతి",
    "हनुमान","आंजनेय","मारुति","बजरंगबली",
  ],
  surya: [
    "surya","suryanarayana","suryanarayan","sun god","ravi",
    "సూర్య","సూర్యనారాయణ","సూర్యుడు",
    "सूर्य","सूर्यनारायण",
  ],
  ayyappa: [
    "ayyappa","ayyappan","sastha","sasta","sabarimala","manikanta",
    "అయ్యప్ప","అయ్యప్పన్","శాస్త","సాస్తా","మణికంఠ",
    "अयप्पा","अय्यप्पन","शास्ता","मणिकंठ",
  ],
};
